name: app_doc
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.2
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_storage: ^11.5.2
  sign_in_button: ^3.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.4
  google_sign_in: ^6.1.6
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  video_player: ^2.8.2
  provider: ^6.1.1
  firebase_database: ^10.4.0
  camera: ^0.10.5+9
  flutter_layout_grid: ^2.0.5
  dotted_border: ^2.1.0
  percent_indicator: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_intl:
  enabled: true
  # Opcional
  # Default: en
  # <language code> [_<script code>][_<country code>]
  main_locale: en

  # Opcional
  # Default: S
  # Suggested alternative name: AppLocalizations
  class: S